### ISSUE TITLE
[MOCO] Activity started from "Todays Activities" not added to list

### ISSUE THREAD

**Issue by mrohlof-protofy** [eviscares/extensions#12] opened 2023-03-14 12:35 UTC
### Extension

https://www.raycast.com/eviscares/moco

### Description

As it says in the title

### Steps To Reproduce

1. Go to "Todays Activities"
2. Start "+ New Activity"
3. Enter any data to form
4. Start Activity via Command+Enter

### Current Behaviour

1. The UI takes you back to "Todays Activities"
2. The activity started in 'Steps To Reproduce 3.' is not shown in the list of "Todays Activities"

### Expected Behaviour

1. The UI takes you back to "Todays Activities"
2. The activity started in 'Steps To Reproduce 3.' is shown and active in the list of "Todays Activities"

**Comment by mrohlof-protofy** [comment] 2023-03-14 15:19
ah, dupe of https://github.com/eviscares/extensions/issues/5?

**Comment by eviscares** [comment] 2023-04-27 08:38
Yup, this is a dupe of #5. I'll ask someone who is a frontend person how to tackle this well.

**Closed as completed by eviscares** 2023-04-27 08:38 UTC
Labels: bug
